### ISSUE TITLE
Wrye Flash does not sort false flagged ESP files among ESM files

### ISSUE THREAD

**Issue by Sharlikran** [Wrye-Bashers/Wrye-Flash-FalloutNV#3]
@valda I have been trying to see where the code sorts false flagged esp files and I have narrowed down where it's happening.

``` python
    def getOrdered(self,modNames,asTuple=True):
        """Sort list of mod names into their load order."""
        data = self.data
        modNames = list(modNames) #--Don't do an in-place sort.
        modNames.sort()
        modNames.sort(key=lambda a: (a in data) and data[a].mtime) #--Sort on modified
        modNames.sort(key=lambda a: a.cs[-1]) #--Sort on esm/esp
        if asTuple: return tuple(modNames)
        else: return modNames
```

That seems to control how the mods are sorted.  Specifically the line `modNames.sort(key=lambda a: a.cs[-1]) #--Sort on esm/esp`.  If I change that line to `modNames.sort(key=lambda a: self[a].isEsm())` that causes all the false flagged files to load last on the mods tab and you can't drag them anywhere else.  So That seems to be where the error is.

Can you help me get the code changed to where it will allow the false flagged files to be sorted among the ESM files?  

I noticed that version 295 was the last version that was Oblivion only.  I tested 295 with an ESP and a false flagged file and it has the same behavior as Wrye Flash.  Starting with 295 and testing all the 295.x revisions I noticed that Wrye Bash 296 was the first version that automatically sorted the ESM and the false flagged ESP files together but the code changes were too different.

I can't copy the boss32.dll and the boss64.dll for 296 to the Wrye Flash folder because of the changes.  The python code might have to be updated a lot or only slightly I'm not sure.

Updated 306 for Fallout support still makes the most sense to do that instead of trying to update the older versions.  However, Utumno is changing 306 a lot and removing some of the lobloadorder dependencies so that Wrye Bash goes back to managing the load order itself and not using the DLL.  That along with other changes have made it a little unstable until he is finished.

The other reason I kinda want to get this working is that your versions are pretty solid.  In fact the only issue is the false flagged files at the moment.  WrinklyNinja no longer wishes to add XP support to the BOSS or LOOT API so for people running Fallout 3 under windows XP they will not be able to use Wrye Flash/Bash.

**Comment by Sharlikran** [comment]
Under class FileInfo: there are two routines, def isEsp(self): and def isEsm(self): and I wonder is there a way to use those two so that the ESM files are first then the ESP files?

``` python
    def getOrdered(self,modNames,asTuple=True):
        """Sort list of mod names into their load order."""
        data = self.data
        modNames = list(modNames) #--Don't do an in-place sort.
        modNames.sort()
        modNames.sort(key=lambda a: (a in data) and data[a].mtime) #--Sort on modified
        #modNames.sort(key=lambda a: a.cs[-1]) #--Sort on esm/esp
        modNames.sort(key=lambda a: self[a].isEsm())
        modNames.sort(key=lambda a: self[a].isEsp())
        if asTuple: return tuple(modNames)
        else: return modNames
```

Doing that didn't break it but it didn't fix it either.

**Comment by valda** [comment]
I do not know what the problem in current code. Now it will normalize the load order by the following process.

Filename ->  Timestamp ->  Last letter of the file-extension (m or p).

How do you want to change this?

**Comment by Sharlikran** [comment]
### Current Code:

``` python
    def getOrdered(self,modNames,asTuple=True):
        """Sort list of mod names into their load order."""
        data = self.data
        modNames = list(modNames) #--Don't do an in-place sort.
        modNames.sort()
        modNames.sort(key=lambda a: (a in data) and data[a].mtime) #--Sort on modified
        modNames.sort(key=lambda a: a.cs[-1]) #--Sort on esm/esp
        if asTuple: return tuple(modNames)
        else: return modNames
```

For now that's the code still.  I didn't change it in bosh.py.  When the file name is .esm or the file name ends in .esp but the header.flags1.esm flag is set those files need to sort as ESM master files.

**Change it to something like**

``` python
 def getOrdered(self,modNames,asTuple=True):
        """Sort list of mod names into their load order."""
        data = self.data
        modNames = list(modNames) #--Don't do an in-place sort.
        modNames.sort()
        modNames.sort(key=lambda a: (a in data) and data[a].mtime) #--Sort on modified
        modNames.sort with .esm extension or .esp extension when header.flags1.esm is set to 1
        modNames.sort with .esp
        if asTuple: return tuple(modNames)
        else: return modNames
```

**Current Sorting:**

FalloutNV.esm
{{{all .esm files}}}
{{{.esp files with header.flags1.esm flag set}}}
{{{all remaining .esp files}}}

### Allow false flagged .esp files to sort among .esm files:

**Expected sorting:**

FalloutNV.esm
{{{all .esm files **OR .esp** files with **header.flags1.esm** flag set}}}
{{{all remaining .esp files}}}

When I try to drag an .esp file with the header.flags1.esm flag set it should be allowed to move into the ESM master file section because the header.flags1.esm flag set.

For example:
![image](https://cloud.githubusercontent.com/assets/1912426/8143059/43639302-114e-11e5-86fb-87437fa0dd27.png)

Project Nevada - Rebalance.esp and Project Nevada - Cyberware.esp are false flagged files.

![image](https://cloud.githubusercontent.com/assets/1912426/8143063/6feabfa4-114e-11e5-8bf8-ec1b66f07bda.png)

They should be able to be moved up among the ESM files.  LOOT and BOSS will sort them there but then Wrye Flash will will place them after the ESM files.

**Comment by valda** [comment]
You'd like to sort by the header esm flag, not an extension?
I think that is routine which should be changed too. But, there seems to be a routine limiting the order of lists as well as it.
I also investigate.

**Comment by Sharlikran** [comment]
The 296 code for Oblivion/Skyrim version is the newest that works correctly and only uses boss32.dll and boss64.dll.  If you use the DLL from 296 then there is an `oblivionworks\Tags\Wrye Bash\296\Mopy\bash\compiled\Microsoft.VC80.CRT`.  I would have to packadge that with Wrye Flash and inform users of the change.

Thanks for helping.  I like to keep this version working for current users.  I will resume work on 306 later because that still needs to be finished.

**Comment by valda** [comment]
Paste the diff so could not push.

``` diff
diff --git a/Mopy/bash/basher.py b/Mopy/bash/basher.py
index 9ce70f2..86ed18d 100644
--- a/Mopy/bash/basher.py
+++ b/Mopy/bash/basher.py
@@ -1483,12 +1483,18 @@ class ModList(List):
         # Make sure we don't go out of bounds
         target = indexes[0]
         thisFile = self.items[target]
+        def isEsp(file):
+            if thisFile in bosh.modInfos:
+                return bosh.modInfos[thisFile].isEsp()
+            else:
+                return None
+        thisFileIsEsp = isEsp(thisFile)
         while True:
             if target < 0: break
             if target + howMany >= len(self.items) - inc: break
             if target == newPos: break
             swapFile = self.items[target]
-            if thisFile.cext != swapFile.cext: break
+            if thisFileIsEsp != isEsp(swapFile): break
             target += inc
         if inc == 1 and target + howMany <= indexes[-1]: return
         if inc == -1 and target >= indexes[0]: return
@@ -1704,7 +1710,7 @@ class ModList(List):
         #--ESMs First?
         settings['bash.mods.esmsFirst'] = self.esmsFirst
         if self.esmsFirst or col == 'Load Order':
-            self.items.sort(key = lambda x: x.cext)
+            self.items.sort(key = lambda x: (x in bosh.modInfos) and bosh.modInfos[x].isEsp())
         #--Selected First?
         settings['bash.mods.selectedFirst'] = self.selectedFirst
         if self.selectedFirst:
diff --git a/Mopy/bash/bosh.py b/Mopy/bash/bosh.py
index 31a5d21..a5a5bff 100644
--- a/Mopy/bash/bosh.py
+++ b/Mopy/bash/bosh.py
@@ -11910,9 +11910,10 @@ class ModInfos(FileInfos):
         """Sort list of mod names into their load order."""
         data = self.data
         modNames = list(modNames) #--Don't do an in-place sort.
-        modNames.sort()
+        #modNames.sort()
         modNames.sort(key=lambda a: (a in data) and data[a].mtime) #--Sort on modified
-        modNames.sort(key=lambda a: a.cs[-1]) #--Sort on esm/esp
+        #modNames.sort(key=lambda a: a.cs[-1]) #--Sort on esm/esp
+        modNames.sort(key=lambda a: (a in data) and data[a].isEsp())
         if asTuple: return tuple(modNames)
         else: return modNames
```

**Comment by Sharlikran** [comment]
@valda please try to push so I don't make mistake with code.  Then I will test.

**Comment by Sharlikran** [comment]
@valda It works, you are so awesome.  I will make updates for Nexus so that FO3 and FNV users have this it has been needed for a long time.

**Comment by valda** [comment]
That's a good idea. I think the FO3/NV player is increasing after the announcement of Fallout4. I want new version that supports LOOT too :smile:

**Comment by Sharlikran** [comment]
Yeah I had wanted to try and add loot to your version but I am not sure about doing that.  The reason is that Wrinkly has no interest in maintaining XP support for LOOT API.  I think leandor explained it best on the Wrye Bash repo.  He believes it's because of updated MS CRT dependencies that don't exist for XP.  So the LOOT API code would have to be rewritten to work with older dependencies that are also XP compatible.

**Comment by Sharlikran** [comment]
I have updated the files on the nexus.  Download them and use 7Zip to test the integrity of the archive.  Sometimes when I upload files to the Nexus they end up corrupted.  This does not happen on Microsoft OneDrive, GitHub, or MediaFire only Nexus but they are not going to look into it.

Also I have updated the Releases for both versions on the GitHub so users can download from the GitHub as a Mirror.

[WF FO3](https://github.com/Wrye-Bashers/Wrye-Flash-Fallout3/releases)
[WF FNV](https://github.com/Wrye-Bashers/Wrye-Flash-FalloutNV/releases)

**Comment by Sharlikran** [comment]
@valda 

This does not seem related to your update.  Do you know why it might be there for 30.4 and not 30.3?

``` Python
Traceback (most recent call last):
File "wx\_misc.pyo", line 1358, in Notify
File "wx\_core.pyo", line 14771, in Notify
File "bash\basher.pyo", line 3066, in OnDropFiles
File "bash\basher.pyo", line 3279, in OnShow
File "bash\bosh.pyo", line 14377, in refresh
File "bash\bosh.pyo", line 14570, in refreshInstallers
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)
```

From the Nexus [FO3 Wrye Flash](http://www.nexusmods.com/fallout3/mods/11336/?):

Russian version (31.4 standalone) does not work, only English, 30.3 "non-standalone" with the same translation work fine.

**Comment by valda** [comment]
Is wxPython unicode version bundled with the standalone? Maybe resolve by command-line arg '-U','--Unicode' or set the bEnableUnicode option to True in bash.ini.
I think this option might be better of True by default because it doesn't matter either in ASCII character area.
